version: "1.0"
type: route
data:
  url: "/services/writecache/settings"
  title: _("WriteCache")
  editing: true
  notificationTitle: _("Write Cache settings")
  component: omv-services-writecache-settings-form-page
