#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
  configure)
    # Activate package triggers.
    dpkg-trigger update-workbench

    timer="/etc/systemd/system/omv-writecache-flush.timer"
    if [ -f "${timer}" ]; then
      rm -f "${timer}"
      systemctl daemon-reload
    fi

    # Initialize and migrate configuration database.
    echo "Updating configuration database ..."
    omv-confdbadm create "conf.service.writecache"
    if [ -n "$2" ]; then
      omv-confdbadm migrate "conf.service.writecache" "${2}"
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
